a = input("Digite alguma coisa: ")
print('O tipo primitivo desse valor é {}'.format(type(a)))
print('Só tem espaços? {}'.format(a.isspace()))
print('O valor é número? {}'.format(a.isnumeric()))
print('O valor é alfabético? {}'.format(a.isalpha()))
print('O valor é alfanumérico? {}'.format(a.isalnum()))
print('Está em maiúsculas? {}'.format(a.isupper()))
print('Está em minúscula? {}'.format(a.islower()))
print('Está capitalizada? {}'.format(a.istitle()))